### ISSUE TITLE
Version/release tag

### ISSUE THREAD

**Issue by shiozaki** [quantumlib/OpenFermion-FQE#105]
Hi @ncubin and co - Now that we have bumped the version to 0.2.0, we probably want to tag 0.1.0 (and when you sign off on the release, 0.2.0) for future references?

**Comment by ncrubin** [comment]
Still should add Cython to the requirements.  I'll do that now before pushing to pypi

**Comment by shiozaki** [comment]
Great, thank you. If you recall which hash the 0.1.0 release was, it would be great to make it on Github as well (there are multiple commits on March 6th, 2020 and I haven't been able to extract that information from pypi).

**Comment by ncrubin** [comment]
ah, yes, I will update that as well.  the commit ID should also be listed on pypi.  I'll download the wheels and source from there and postin in the version 0.1.  Then I'll cut a new 0.2 release and push to pypi.  There is one outstanding issue we are working out on tensorflow docs.  Making sure that is resolved before pypi push.

**Comment by ncrubin** [comment]
Just FYI: The old commit that is on pypi 0.1.0 is d00f1fcf852d300a36bad40062f3efe502b243c5.

**Comment by ncrubin** [comment]
creating a release from the v0.1.0 tag makes github list that release first (despite 0.2.0 being more recent).  So I'm going to let it sit tagged but not on the release list.
