### ISSUE TITLE
Upgrade to cirq ~=0.13

### ISSUE THREAD

**Issue by BastianZim** [quantumlib/OpenFermion-FQE#118]
Hi,

I have a couple of projects where I'm using FQE and also need to use `cirq >=0.13`. Would it be possible to release a new version of FQE that supports that?

Thanks!

**Comment by ncrubin** [comment]
Hi @BastianZim , This should be doable.  We'll look into what needs to change with the most recent version of cirq.

**Comment by BastianZim** [comment]
Thank you! :)

**Comment by mpharrigan** [comment]
I'd strongly advocate for un-pinning the exact cirq version from `install_requires` unless a real incompatibility is discovered

**Comment by mpharrigan** [comment]
bump; we're now on cirq 0.14

**Comment by wjhuggins** [comment]
Should be closed by #121.

**Comment by mpharrigan** [comment]
That change just loosens it to 0.12.* instead of 0.12.0, see PR for my comment

**Comment by ncrubin** [comment]
I think yes

**Comment by ncrubin** [comment]
Just tested this with #121. Install and tests are working with cirq versioning for openfermion (currently >=0.12,<=0.14)
