### ISSUE TITLE
Use either pytest or unittest, not both

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/OpenFermion-FQE#38]
Currently everything in algorithm/ uses pytest for testing while everything in fqe_ops/ uses unittest. Is there a reason for using both? AFAIK it's standard to only use one.

**Comment by shiozaki** [comment]
@rmlarose @ncrubin just a heads-up: On the basis of the above conversation, we are migrating all of the tests to pytest. This is also useful in testing both python and c code path in the C-accelerated FQE. The migration will be included in the delivery of the C-accelerated FQE scheduled at the end of this month.
