### ISSUE TITLE
Add tests to FQE control

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/OpenFermion-FQE#55]
Coverage is pretty low in [_fqe_control_test.py](https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/_fqe_control_test.py). 

I haven't gone through everything yet, but it seems like getter methods which just wrap class constructors in _fqe_control.py, e.g. https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/_fqe_control.py#L392, could be removed as an alternative to increasing coverage.

**Comment by shiozaki** [comment]
Will be addressed in the delivery of the C-accelerated FQE.
