### ISSUE TITLE
Fermi-Hubbard simulation example: Low filling is called when half filling should be

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/OpenFermion-FQE#86]
This comes from an example simulating the Fermi-Hubbard model where the time-evolved wavefunction is incorrect.

```python
import numpy as np
from scipy.linalg import expm

import openfermion as of
import fqe

hubbard = of.fermi_hubbard(1, 4, tunneling=1.0, coulomb=2.0, periodic=False)

init_wfn = fqe.Wavefunction([[2, 0, 4]])
init_wfn.set_wfn(strategy="random")

evolved_wfn = init_wfn.time_evolve(1.0, hubbard)

# Check.
wfn_cirq = fqe.to_cirq(init_wfn)
unitary = expm(-1j * of.get_sparse_operator(hubbard))
evolved_wfn_cirq = unitary @ wfn_cirq

fidelity = abs(fqe.vdot(evolved_wfn, fqe.from_cirq(evolved_wfn_cirq, thresh=1e-12)))**2
assert np.isclose(fidelity, 1.0)  # Fails
```

A hack to ensure the fidelity is one is setting `init_wfn.sector((2, 0))._low_thresh = 0.0` before calling `init_wfn.time_evolve`. This causes `time_evolve` to call [`FqeData._apply_array_spin12_halffilling`](https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/fqe_data.py#L375) which produces the correct wavefunction. Without setting the threshold to zero, [`FqeData._apply_array_spin12_lowfilling`](https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/fqe_data.py#L373) is called and results in an incorrect wavefunction.

**Comment by shiozaki** [comment]
The low filling code requires certain index symmetry to be satisfied. See the symmetric action blocks in full = True in https://github.com/quantumlib/OpenFermion-FQE/blob/master/src/fqe/unittest_data/build_hamiltonian.py

The result from half filling and low filling should be identical regardless of the Hamiltonians and wavefunction.

**Comment by rmlarose** [comment]
Thanks @shiozaki. So this is improper usage and not a bug? I'm still confused why the time evolution is incorrect (unless I set `init_wfn.sector((2, 0))._low_thresh = 0.0`).

**Comment by shiozaki** [comment]
Improper usage. Sorry but I’m at a hospital now; will get back next week. Please take a look at test cases.

**Comment by rmlarose** [comment]
> Improper usage. Sorry but I’m at a hospital now; will get back next week. Please take a look at test cases.

Will close then, thanks! More importantly, hope all is well!! No rush here at all.

**Comment by shiozaki** [comment]
@rmlarose I took a look now, it seems this is not intended behavior. I believe that the low-filling code itself is working correctly, but the code that converts FermionOperator to numpy arrays seems to have a problem. Let me take a look.
