### ISSUE TITLE
Upgrade to use Cirq 0.11

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion-FQE#90]
I think cirq.Qid isn't directly compatible so we'll need to make some changes within FQE.

**Comment by rmlarose** [comment]
I assume we tried the same thing which led to an `AttributeError` with `cirq.Qid`. Interestingly this had nothing to do with `cirq.Qid` but rather a broken Cirq installation.

```bash
pip install openfermion==1.0.0  # Installs cirq==0.10.0
pip install cirq==0.11.0
```

At this point the Cirq installation is no bueno. 

```python
import cirq
cirq.Qid  # AttributeError: module 'cirq' has no attribute 'Qid'
cirq.Circuit  # AttributeError: module 'cirq' has no attribute 'Circuit'
cirq.__version__  # AttributeError: module 'cirq' has no attribute '__version__'
```

cc @balopat as an FYI, maybe this will pop up elsewhere?

**Comment by ncrubin** [comment]
a new version of openfermion as been pushed to pypi 1.1.0 which functions with cirq.0.11.0. Moving forward we need to force FQE to use these versions.

**Comment by rmlarose** [comment]
Thanks @ncrubin - Done in #91!
