### ISSUE TITLE
Pip install failing

### ISSUE THREAD

**Issue by rmlarose** [quantumlib/OpenFermion-FQE#95]
Currently, `pip install fqe` fails with

`ERROR: openfermion 1.0.1 has requirement cirq==0.10.0, but you'll have cirq 0.11.0 which is incompatible.`

I noticed [requirements.txt](https://github.com/quantumlib/OpenFermion-FQE/blob/master/requirements.txt#L1) lists `cirq~=0.10` causing Cirq 0.11 to get installed, but this clashes with the OpenFermion requirement of Cirq 0.10.

Can be fixed by a new OpenFermion release or a patch FQE release where requirements.txt is updated to `cirq~=0.10.0`. xref #91

**Comment by ncrubin** [comment]
we should upgrade cirq~=0.11.0 and openfermion==1.1.0.

These are now live on pypi and thus should resolve this issue.
